services:
  db:
    image: postgres:15
    restart: always
    container_name: invsto_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invsto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  backend:
    build: .
    container_name: invsto_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=invsto
      - DB_USER=postgres
      - DB_PASSWORD=postgres

volumes:
  postgres_data:
